--债权来源
INSERT INTO COM_T_PARAM (ID,TYPE, TYPE_NAME, PARAMETER_NAME, VALUE, PARENT_ID, SORT, IS_EDIT, STATUS, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID,VERSION, MEMO)
VALUES ('20150423','BAO_LOAN_SOURCE', '债权来源', '善林金额', '1', '0', 1, 0, '1', SYSDATE, '', NULL, 'SYSTEM', '0','');


INSERT INTO BAO_T_PRODUCT_TYPE_INFO (ID, TYPE_NAME, TYPE_STATUS, INCOME_TYPE, INCOME_HANDLE_METHOD, ALREADY_PRE_VALUE, EXPECT_PRE_VALUE, ENABLE_STATUS, RECORD_STATUS, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE, VERSION, MEMO)
VALUES ('P00001', '善林财富', '正常', '非固定类', NULL, 0.00000000, 0.00000000, '启用', NULL, NULL, SYSDATE, NULL, SYSDATE, 0, NULL);

INSERT INTO BAO_T_PRODUCT_TYPE_INFO (ID, TYPE_NAME, TYPE_STATUS, INCOME_TYPE, INCOME_HANDLE_METHOD, ALREADY_PRE_VALUE, EXPECT_PRE_VALUE, ENABLE_STATUS, RECORD_STATUS, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE, VERSION, MEMO)
VALUES ('P00002', '善林理财', '正常', '固定类', NULL, 0.00000000, 0.00000000, '启用', NULL, NULL, SYSDATE, NULL, SYSDATE, 0, NULL);

INSERT INTO BAO_T_CUST_INFO (ID, LOGIN_NAME, LOGIN_PASSWORD, TRADE_PASSWORD, CREDENTIALS_TYPE, CREDENTIALS_CODE, CUST_NAME, CUST_CODE, BIRTHDAY, CUST_LEVEL, SAFE_LEVEL, CUST_GENDER, CUST_SOURCE, CUST_TYPE, NATVICE_PLACE_PROVINCE, NATVICE_PLACE_CITY, NATVICE_PLACE_COUNTY, NATVICE_PLACE_AREA, COMMUN_ADDRESS, MOBILE, EMAIL, PORTRAIT_PATH, REAL_NAME_AUTH_COUNT, IS_LUMPER, MSG_ON_OFF, ENABLE_STATUS, RECORD_STATUS, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE, VERSION, MEMO)
VALUES ('C00001', '周伯云', '111111', '111111', '1', '320223196701217075', '周伯云', '1000001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, SYSDATE, NULL, SYSDATE, 0, NULL);

INSERT INTO BAO_T_ACCOUNT_INFO (ID, CUST_ID, ACCOUNT_NO, ACCOUNT_TOTAL_AMOUNT, ACCOUNT_FREEZE_AMOUNT, ACCOUNT_AVAILABLE_AMOUNT, ACCOUNT_TYPE, RECORD_STATUS, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE, VERSION, MEMO)
VALUES ('A00001', 'C00001', 'ACCT000001', 0, 0, 0, '居间人账户', '有效', 'SYSTEM', SYSDATE, NULL, NULL, 0, NULL);

INSERT INTO BAO_T_ACCOUNT_INFO (ID, CUST_ID, ACCOUNT_NO, ACCOUNT_TOTAL_AMOUNT, ACCOUNT_FREEZE_AMOUNT, ACCOUNT_AVAILABLE_AMOUNT, ACCOUNT_TYPE, RECORD_STATUS, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE, VERSION, MEMO)
VALUES ('A00002', 'C00001', 'ACCT000002', 0, 0, 0, '公司收益账户', '有效', 'SYSTEM', SYSDATE, NULL, NULL, 0, NULL);


INSERT INTO BAO_T_SUB_ACCOUNT_INFO (ID, CUST_ID, ACCOUNT_ID, RELATE_TYPE, RELATE_PRIMARY, SUB_ACCOUNT_NO, ACCOUNT_TOTAL_VALUE, ACCOUNT_FREEZE_VALUE, ACCOUNT_AVAILABLE_VALUE, ACCOUNT_AMOUNT, RECORD_STATUS, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE, VERSION, MEMO)
VALUES ('SA0001', 'C00001', 'A00001', 'BAO_T_PRODUCT_TYPE_INFO', 'P00001', 'SACCT00001', 0.00000000, 0.00000000, 0.00000000, 0.00000000, NULL, NULL, SYSDATE, NULL, NULL, NULL, NULL);

INSERT INTO BAO_T_SUB_ACCOUNT_INFO (ID, CUST_ID, ACCOUNT_ID, RELATE_TYPE, RELATE_PRIMARY, SUB_ACCOUNT_NO, ACCOUNT_TOTAL_VALUE, ACCOUNT_FREEZE_VALUE, ACCOUNT_AVAILABLE_VALUE, ACCOUNT_AMOUNT, RECORD_STATUS, CREATE_USER, CREATE_DATE, LAST_UPDATE_USER, LAST_UPDATE_DATE, VERSION, MEMO)
VALUES ('SA0002', 'C00001', 'A00002', 'BAO_T_PRODUCT_TYPE_INFO', 'P00002', 'SACCT00002', 0.00000000, 0.00000000, 0.00000000, 0.00000000, NULL, NULL, SYSDATE, NULL, NULL, NULL, NULL);




INSERT INTO COM_T_PARAM(ID,TYPE,TYPE_NAME,PARAMETER_NAME,VALUE,PARENT_ID,SORT,IS_EDIT,STATUS,CREATE_USER_ID,CREATE_DATE,UPDATE_USER_ID,UPDATE_DATE,VERSION,MEMO)
VALUES(1000,'baoLoanAssetType','资产类型','基金','基金',NULL,NULL,'0','1','ADMIN',SYSDATE,'ADMIN',SYSDATE,0,'');

INSERT INTO COM_T_PARAM(ID,TYPE,TYPE_NAME,PARAMETER_NAME,VALUE,PARENT_ID,SORT,IS_EDIT,STATUS,CREATE_USER_ID,CREATE_DATE,UPDATE_USER_ID,UPDATE_DATE,VERSION,MEMO)
VALUES(1001,'baoLoanAssetType','资产类型','信托','信托',NULL,NULL,'0','1','ADMIN',SYSDATE,'ADMIN',SYSDATE,0,'');

INSERT INTO COM_T_PARAM(ID,TYPE,TYPE_NAME,PARAMETER_NAME,VALUE,PARENT_ID,SORT,IS_EDIT,STATUS,CREATE_USER_ID,CREATE_DATE,UPDATE_USER_ID,UPDATE_DATE,VERSION,MEMO)
VALUES(1002,'baoLoanAssetType','资产类型','配资','配资',NULL,NULL,'0','1','ADMIN',SYSDATE,'ADMIN',SYSDATE,0,'');